### PR TITLE
fix(fe/user): Remove placeholders for user's first and last names

### LINKED ISSUE #1920: Sign up - Remove the default text for first and last name
Please remove the default texts - they add nothing!

login-comment2

### PR DESCRIPTION
**Pull request by johnnynotsolucky**
Closes #1920

### CODE REVIEW

File: frontend/apps/crates/entry/user/src/register/pages/step_1/dom.rs [hunk 1]
```diff
@@ -25,13 +25,6 @@ impl Step1Page {
                     .property_signal("hint", state.firstname_error())
                     .child(html!("input" => HtmlInputElement, {
                         .with_node!(elem => {
-                            .property("placeholder", STR_FIRSTNAME_PLACEHOLDER)
-                            .property("value", &*state.firstname.borrow())
-                            .event(clone!(state, elem => move |_:events::Input| {
-                                state.clear_firstname_status();
```
Comment (johnnynotsolucky) [inline frontend/apps/crates/entry/user/src/register/pages/step_1/dom.rs:31]: This was a duplicated block of code. Removed it.
