### PR TITLE
Incomplete error tooltip

### LINKED ISSUE #2216: Shouldn't be possible to preview or publish an empty JIG, or a JIG which has a module with no content
**Describe the bug**

A JIG can be published without having any modules added. It can also be published with modules which have no content.

**To Reproduce**

1. Create a new JIG
2. Click Publish
3. Allows you to publish

**Expected behavior**

Shouldn't be able to navigate to the publish screen.

**Additional context**

This should apply to Preview JIG as well - Shouldn't be able to preview a JIG with no modules or modules with no content.

---

- [x] Update related endpoints so that module data includes `is_complete`
- ~[x] In the JIG edit sidebar, change the color of a JIG to red (instead of blue) if there's no content yet;~
  - [x] Update to remove the red color
- [x] Prevent them from publishing until all activities have content set.
  - [x] Update the publish endpoint so that it is not possible to publish when a JIG has incomplete modules
- [x] When previewing a JIG, render a new graphic on modules without content to illustrate that it is waiting for content.
- [x] Update `is_complete()` rules for each game type so that the minimum requirements are met for that type
- [x] On the publish screen notify the teacher that there are modules without content

### PR DESCRIPTION
**Pull request by johnnynotsolucky**
Closes #2216 

- Adds error tooltip to the first incomplete module in a JIG when the teacher clicks publish but has incomplete modules;
- Highlights incomplete modules in red;
- Scrolls to first incomplete module when clicking publish;
- Adds error tooltip to Publish window in the sidebar if the teacher clicks publish without adding any activities or a cover;
- Disables the publish button on the publish screen if the teacher hasn't added any activities or a cover.

Outstanding:
- [ ] ~Work out how to get the left-pointing arrow to show up;~
  - Currently only the up and down arrows show up when tracking the position of the module in the sidebar.
  - I have a draft PR with a POC refactor of tooltips to make them more practical: #2322 
- [x] Close the tooltip when the teacher clicks anywhere (or worst-case, just on the tooltip itself).

### Current progress:

image

### CODE REVIEW

File: frontend/apps/crates/entry/jig/edit/src/edit/publish/dom/mod.rs [hunk 1]
```diff
@@ -240,7 +240,12 @@ fn render_page(state: Rc<Publish>) -> Dom {
                     .child(html!("button-rect", {
                         .text(STR_PUBLISH)
                         .text(state.jig.focus_display())
-                        .property("disabled", state.jig.modules.lock_ref().iter().find(|m| !m.is_complete).is_some())
+                        .property(
```
Comment (johnnynotsolucky) [inline frontend/apps/crates/entry/jig/edit/src/edit/publish/dom/mod.rs:243]: Even though the teacher won't be able to navigate to the publish screen via the sidebar, if they know to add /publish to the url, they'll see the screen. This is a safety check.
