### PR TITLE
fix(fe/jig/play): Add missing robot feet in sidepanel

### LINKED ISSUE #2078: Legacy games - Add legs of the JIG under the last activity
This is what we see now:
Screen Shot 2021-12-22 at 20 04 11

Pls place the illustration used in the other games:
Screen Shot 2021-12-22 at 20 01 49

### PR DESCRIPTION
**Pull request by johnnynotsolucky**
Resolves #2078

image

### CODE REVIEW

File: frontend/elements/src/entry/jig/_common/sidebar-modules/module.ts [hunk 1]
```diff
@@ -210,6 +219,37 @@ export class _ extends LitElement {
...
+
+        if (this.index === 0) {
+            return html`
+                ${getImage("arm-left.svg", "arm-left")}
+                ${getImage("arm-right.svg", "arm-right")}
+                ${getImage("neck-spring.svg", "neck")}
+                ${getImage("yellow/face.png", "head")}
+                ${getImage("torso-columns.svg", "torso-columns")}
+            `;
+        } else if (this.lastBottomDecoration) {
```
Comment (johnnynotsolucky) [inline frontend/elements/src/entry/jig/_common/sidebar-modules/module.ts:234]: This is new code. Otherwise this whole change is moving the renderDecorations into inside the element class.
